trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'my_group'  

stages:
- stage: ReadSecrets
  jobs:
  - job: ReadSecrets
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'azure-service-connection'
        KeyVaultName: 'dev-eic-mykeyvaulty100'
        SecretsFilter: '*' # 'mysecret'
        RunAsPreJob: false

    # - script: |
    #     echo "##vso[task.setvariable variable=MY_SECRET_VAR;issecret=true]$(MY_SECRET_NAME)"
    #   displayName: 'Store secrets in variable group'
    - script: |
          echo $(mysecret)