trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'my_group'  

stages:
- stage: ReadSecrets
  jobs:
  - job: ReadSecrets
    steps:
    - script: |
          echo $(dev-eic-secret01)