trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'my_group'  

stages:
- stage: ReadSecrets
  jobs:
  - job: ReadSecrets
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'mykeyvault-service'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #!/bin/bash
          
          # names=$(az keyvault secret list --vault-name dev-eic-mykeyvaulty101 --query '[].name' -o tsv)
          az keyvault secret list --vault-name dev-eic-mykeyvaulty101 --query '[].name' -o tsv >> secrets.txt
          # for name in ${names};
          # do
          #     echo "${name//-/_}  ==  ${!name}" >> secrets.txt
          # done

    # - task: CopyFiles@2
    #   displayName: Copy secret files
    #   inputs:
    #     Contents: 'secrets.txt'
    #     TargetFolder: '$(build.artifactstagingdirectory)'
    # - task: PublishBuildArtifacts@1
    #   displayName: Publish Artifacts
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'
      
    - script: |
          #!/bin/bash

          while read -r name
          do
              echo "${name//-/_}  ==  $(name)" >> secrets1.txt
          done < secrets.txt  

    # - script: |
    #       echo $(dev-eic-secret01)

    - task: CopyFiles@2
      displayName: Copy secret files
      inputs:
        Contents: 'secrets1.txt'
        TargetFolder: '$(build.artifactstagingdirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'