apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: myapp-backend
        image: shivmodi1203/myapp-backend
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: myapp-backend-config
