apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: myapp-service
    app: myapp-frontend
spec:
  type: NodePort
  selector:
    app: myapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001